### PR TITLE
Invalid package reference in library; not included in Android: java.nio.file. Referenced from okio.Okio.

### PR DESCRIPTION
**Pull request by shendepu**
When using react-native-simpledialog-android in react native app, running ./gradlew build in android project always fails on "../../../../../../../../../.gradle/caches/modules-2/files-2.1/com.squareup.okio/okio/1.6.0/98476622f10715998eacf9240d6b479f12c66143/okio-1.6.0.jar: Invalid package reference in library; not included in Android: java.nio.file. Referenced from okio.Okio."

### CODE REVIEW

**Comment by lucasferreira** [comment]
Hi @shendepu 

Thanks for your contribution. Can you explain a little more in what kind of situations this error happens?

I've been using this package in lot's of projects, in different versions of React Native and never face this "Invalid package reference in library" problem.

**Comment by shendepu** [comment]
I double checked just now, by checking out fresh copy of snowflake project (https://github.com/bartonhammond/snowflake), and run npm install, then go to android folder, runing "./gradlew build", it still fails at ":RNSimpleAlertDialogModule:lint FAILED", and message is

```
* What went wrong:
Execution failed for task ':RNSimpleAlertDialogModule:lint'.
> java.lang.NullPointerException (no error message)
```

In my project, the lint report says "Invalid package reference in library; not included in Android: java.nio.file. Referenced from okio.Okio." 

After I added lint.xml to ignore "okio-1.6.0.jar" in react-native-simpledialog-android, then ":RNSimpleAlertDialogModule:lint" passed. 

By the way, I think the commit of adding gradle wrapper can be removed, since react native project is using its own gradle wrapper. It would be duplicated and increase size of npm package of react-native-simpledialog-android

**Comment by lucasferreira** [comment]
hi @shendepu 

Thanks again. But, the most strange thing here is that we didn't use "java.nio.file" in Java code:

https://github.com/lucasferreira/react-native-simpledialog-android/blob/master/src/main/java/com/burnweb/rnsimplealertdialog/RNSimpleAlertDialogModule.java
https://github.com/lucasferreira/react-native-simpledialog-android/blob/master/src/main/java/com/burnweb/rnsimplealertdialog/RNSimpleAlertDialogPackage.java

Would you think that this error is happening only inside snowflake project?

**Comment by shendepu** [comment]
Maybe some intermediate component depends on it, then the lint error pop up. and it's only happens through running ./gradlew build in android folder. 

As I understand, when build through Android Studio, lint check configuration in Android Studio also takes effect, so the it does not fail at ":RNSimpleAlertDialogModule:lint", but running through gradle build, it has no access to Android Studio lint configuration, so it fails. To ignore this, lint.xml has to be configured.

**Comment by lucasferreira** [comment]
Thanks @shendepu 

I had merged your PR, but I remove the graddle wrapper, adding only the lint.xml config.

Can you update your module install and testing again?

**Comment by shendepu** [comment]
I tested it. lint runs ok with gradle 2.2 and 'com.android.tools.build:gradle:1.1.3', but fails with gradle 2.10 and 'com.android.tools.build:gradle:2.0.0'. 

Since the gradle wrapper in react native project is using 'com.android.tools.build:gradle:2.0.0' that uses gradle 2.10, :RNSimpleAlertDialogModule:lint task still fails. 

Currently I add augment in command line "./gradlew build -x :RNSimpleAlertDialogModule:lint" so the command line build can pass. 

And one strange thing I found is if I open the project with Android Studio, then command line build can pass. But anyway this can't help the CI.

**Comment by shendepu** [comment]
Finally I catch the root cause of why command line './gradlew build' passes if open with android studio once. Open with android studio automatically put local.properties file on disk with sdk.dir referencing to android sdk location. Without this variable, lint tasks fail. 

So in CI, I can add sdk.dir in environment variable, then run './gradlew build'.

**Comment by lucasferreira** [comment]
OK @shendepu 

I used to run using or Android Studio or 'react-native run-android' command. And there are no problems at all.

**Pull request merged**
